### ISSUE TITLE
Issues with WinHttpRequest.ahk

### ISSUE THREAD

**Issue by lingojourney** [htadashi/GPT3-AHK#6] opened 2023-04-21 22:50 UTC
Dear Team,

I hope this message finds you well. I am reaching out to you regarding an issue I encountered while working on the Git project. Despite not having made any changes, I am encountering an error [1].

I was wondering if you would be open to extending your support and expertise to help me resolve this issue. Your assistance would be immensely appreciated.

Thank you for your time and consideration. I look forward to hearing back from you soon.

Warm regards,
Ben
[1] 
Error: Too many parameters passed to function.
Specifically: StrSplit(part, ’=’,, 2]
Line#
083:{
084: if (IsObject(sData)]
085: Return,sData
086: sData := LTrim(sData, ’?']
087: obj := {}
088: For_,part in StrSpIit[sData, ’8!)
088:{
---> 089: pair 2: StrSpIit[parl:, ’=’,, 2}
090: key := this.DecodeUriComponent(pair[1])
091: val := this.DecodeUriComponent[pair[2]]
092: obj[key] := val
093:}
094: Return,obj
095:}
100:{
The program will exit.

**Comment by htadashi** [comment] 2023-05-06 18:27
Hi @lingojourney, I couldn't reproduce this error on my side. 

I suspect, however, that this issue is related to issue #5 and thus will close this issue as a duplicate from it. Kindly follow the instructions in #5 and please re-open this issue in case this error persists :)

**Closed by htadashi** 2023-05-06 18:27 UTC
